// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tadbeer.DAL.Data;

#nullable disable

namespace Tadbeer.DAL.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260305085555_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken", (string)null);
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.AIDetection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_path");

                    b.Property<Guid>("PredictedSpecialtyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("predicted_specialty_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("aidetection_id_primary");

                    b.HasIndex("PredictedSpecialtyId");

                    b.HasIndex("UserId");

                    b.ToTable("AIDetection", (string)null);
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<long?>("AvgRating")
                        .HasColumnType("bigint")
                        .HasColumnName("avg_rating");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("city");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<long?>("ExperienceYears")
                        .HasColumnType("bigint")
                        .HasColumnName("experience_years");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("job_description");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email_normalized");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("username_normalized");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("profile_image");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("User")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Existed")
                        .HasColumnName("status");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("AvgRating")
                        .HasDatabaseName("applicationuser_avg_rating_index");

                    b.HasIndex("City")
                        .HasDatabaseName("applicationuser_city_index");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("applicationuser_email_unique")
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[username_normalized] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("applicationuser_username_unique")
                        .HasFilter("[username] IS NOT NULL");

                    b.HasIndex("City", "Role")
                        .HasDatabaseName("applicationuser_city_role_index");

                    b.HasIndex("Role", "Status")
                        .HasDatabaseName("applicationuser_role_status_index");

                    b.ToTable("ApplicationUser", null, t =>
                        {
                            t.HasCheckConstraint("CK_ApplicationUser_Role", "[role] IN ('admin','worker','user')");

                            t.HasCheckConstraint("CK_ApplicationUser_Status", "[status] IN ('existed','deleted')");
                        });
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("booking_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("worker_id");

                    b.Property<Guid>("WorkingHourId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("working_hour_id");

                    b.HasKey("Id")
                        .HasName("bookings_id_primary");

                    b.HasIndex("Status")
                        .HasDatabaseName("bookings_status_index");

                    b.HasIndex("UserId")
                        .HasDatabaseName("bookings_user_id_index");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("bookings_worker_id_index");

                    b.HasIndex("WorkingHourId");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_Status", "[status] IN ('pending','accepted','rejected','completed','cancelled')");
                        });
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.PhoneNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("phonenumber_id_primary");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("phonenumber_phone_number_unique");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("phonenumber_worker_id_index");

                    b.ToTable("PhoneNumber", (string)null);
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<byte>("Rate")
                        .HasColumnType("tinyint")
                        .HasColumnName("rate");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("review_id_primary");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("review_booking_id_index");

                    b.ToTable("Review", null, t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rate", "[rate] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("specialty_id_primary");

                    b.ToTable("Specialty", (string)null);
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.WorkImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("workimage_id_primary");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("workimage_worker_id_index");

                    b.ToTable("WorkImage", (string)null);
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.WorkSubImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_url");

                    b.Property<Guid>("MainImageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("main_image_id");

                    b.HasKey("Id")
                        .HasName("worksubimages_id_primary");

                    b.HasIndex("MainImageId")
                        .HasDatabaseName("worksubimages_main_image_id_index");

                    b.ToTable("WorkSubImages", (string)null);
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.WorkerSpecialty", b =>
                {
                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("worker_id");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("specialty_id");

                    b.HasKey("WorkerId", "SpecialtyId");

                    b.HasIndex("SpecialtyId")
                        .HasDatabaseName("workerspecialty_specialty_id_index");

                    b.ToTable("WorkerSpecialty", (string)null);
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.WorkingHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("workinghours_id_primary");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkingHours", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkingHours_DayOfWeek", "[day_of_week] IN ('Saturday','Sunday','Monday','Tuesday','Wednesday','Thursday','Friday')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Tadbeer.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Tadbeer.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tadbeer.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Tadbeer.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.AIDetection", b =>
                {
                    b.HasOne("Tadbeer.DAL.Models.Specialty", "PredictedSpecialty")
                        .WithMany("AIDetections")
                        .HasForeignKey("PredictedSpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tadbeer.DAL.Models.ApplicationUser", "User")
                        .WithMany("AIDetections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PredictedSpecialty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.Booking", b =>
                {
                    b.HasOne("Tadbeer.DAL.Models.ApplicationUser", "User")
                        .WithMany("UserBookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tadbeer.DAL.Models.ApplicationUser", "Worker")
                        .WithMany("WorkerBookings")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tadbeer.DAL.Models.WorkingHours", "WorkingHour")
                        .WithMany("Bookings")
                        .HasForeignKey("WorkingHourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Worker");

                    b.Navigation("WorkingHour");
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.PhoneNumber", b =>
                {
                    b.HasOne("Tadbeer.DAL.Models.ApplicationUser", "Worker")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.Review", b =>
                {
                    b.HasOne("Tadbeer.DAL.Models.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("Tadbeer.DAL.Models.Review", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.WorkImage", b =>
                {
                    b.HasOne("Tadbeer.DAL.Models.ApplicationUser", "Worker")
                        .WithMany("WorkImages")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.WorkSubImage", b =>
                {
                    b.HasOne("Tadbeer.DAL.Models.WorkImage", "MainImage")
                        .WithMany("SubImages")
                        .HasForeignKey("MainImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainImage");
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.WorkerSpecialty", b =>
                {
                    b.HasOne("Tadbeer.DAL.Models.Specialty", "Specialty")
                        .WithMany("WorkerSpecialties")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tadbeer.DAL.Models.ApplicationUser", "Worker")
                        .WithMany("WorkerSpecialties")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialty");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.WorkingHours", b =>
                {
                    b.HasOne("Tadbeer.DAL.Models.ApplicationUser", "Worker")
                        .WithMany("WorkingHours")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.ApplicationUser", b =>
                {
                    b.Navigation("AIDetections");

                    b.Navigation("PhoneNumbers");

                    b.Navigation("UserBookings");

                    b.Navigation("WorkImages");

                    b.Navigation("WorkerBookings");

                    b.Navigation("WorkerSpecialties");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.Booking", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.Specialty", b =>
                {
                    b.Navigation("AIDetections");

                    b.Navigation("WorkerSpecialties");
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.WorkImage", b =>
                {
                    b.Navigation("SubImages");
                });

            modelBuilder.Entity("Tadbeer.DAL.Models.WorkingHours", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
